# Generated by Django 5.1.7 on 2025-03-31 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50, verbose_name='nombre')),
                ('productSize', models.IntegerField(verbose_name='talle')),
                ('productColor', models.CharField(max_length=50, verbose_name='color')),
            ],
            options={
                'verbose_name': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suplierName', models.CharField(max_length=50, verbose_name='proveedor')),
                ('suplierPhone', models.IntegerField(verbose_name='telefono')),
                ('suplierAddress', models.CharField(max_length=50, verbose_name='direccion')),
                ('suplierLocation', models.CharField(max_length=3, verbose_name='provincia')),
            ],
            options={
                'verbose_name': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'pending'), ('c', 'accomplish'), ('r', 'rejected')], max_length=1, verbose_name='estado de orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapamania.suplier', verbose_name='provedor')),
            ],
            options={
                'verbose_name': 'orden',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productQuantity', models.IntegerField(verbose_name='cantidad')),
                ('orderNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapamania.order', verbose_name='numero de orden')),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapamania.product', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'item de la orden',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depQuantity', models.IntegerField(verbose_name='cantidad')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('depProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapamania.product', verbose_name='deposito')),
            ],
            options={
                'verbose_name': 'deposito',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('phone', models.IntegerField(verbose_name='telefono')),
                ('address', models.CharField(max_length=100, verbose_name='direccion')),
                ('userType', models.CharField(choices=[('p', 'provider'), ('c', 'client'), ('a', 'admin'), ('d', 'deposit'), ('s', 'sales')], max_length=1, verbose_name='tipo de usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('order', models.CharField(max_length=50, verbose_name='orden')),
                ('registryOp', models.CharField(choices=[('a', 'alta'), ('b', 'baja')], max_length=1, verbose_name='operacion')),
                ('cause', models.CharField(choices=[('c', 'compra'), ('v', 'venta'), ('d', 'devolucion'), ('e', 'error'), ('o', 'otro')], max_length=1, verbose_name='causa')),
                ('registryProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapamania.product', verbose_name='inventario')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapamania.suplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'registro',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceCoef', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='coeficiente')),
                ('priceProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapamania.product', verbose_name='precio Producto')),
                ('priceSuplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapamania.suplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'precio',
            },
        ),
    ]
